version: "3.9"
services:
  webhook_receiver:
    build: .
    restart: always
    ports:
      - "5065:5065"
    environment:
      FLASK_ENV: development
    env_file:
      - .env
    volumes:
      - ./cert:/app/cert
      - ./data:/app/data
      - ./cred:/app/cred
